config/routes.rb
Rails.application.routes.draw do
  
  root 'groups#index'


  #custom routes:
  #
  #
  get '/groups/:id/join_group', to: 'groups#join_group'
  get '/groups/:id/leave_group', to: 'groups#leave_group'
  get '/groups/recently_active', to: 'groups#recently_active', as: "recently_active"
  get '/search_groups', to: 'groups#search', as: "search_groups"
  get '/search_users', to: 'profiles#search', as: "search_users"



  #omniauth routes:
  get '/auth/facebook/callback' => 'sessions#create'

  
  
  #standard routes:
  

  resources :posts, only: [] do
    resources :comments, except: [:index, :show]
  end
  resources :groups do 
    resources :posts, except: [:index]
  end

  
  
  
  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'callbacks' }
  
  resources :profiles, only: [:show]







  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

    before_action :set_user, only: [:show, :edit, :update]
    before_action :authenticate_user!



    def index
        @users = User.all
    end
  
    def show
      @user_groups = @user.groups
      @user_posts = @user.posts 
      @user_comments = @user.comments
    end
   
   
    def search # note -- there's no search bar in the layout rn bc I'm refactoring. add one back!
      @users = User.where("name LIKE ?", "%#{params[:user_name_q]}%")
      if @users.empty?
        flash.now[:error] = "No results found for '#{params[:user_name_q]}'!" 
      else
        flash.now[:notice] = "Here are your search results for '#{params[:user_name_q]}'."
      end
      render 'index'
    end


    private
      def user_params
        params.require(:user).permit(:name, :bio, :uid)
      end
  
      def set_user
        @user = User.find(params[:id])
      end
  
  end

app/views/profiles/index.html.erb
<h1>Activist Network: User Search Results</h1>

<h3> 

    <%= link_to "Create a Group", new_group_path %>

</h3>

<ul>

    <% @users.each do |user| %>
        <li><%= link_to user.name, profile_path(user) %></li>
        <br>
    <% end %>

</ul>

app/views/profiles/show.html.erb
<h1><%= @user.name %></h1>

<h3>Bio: <%= @user.bio %></h3>

<% if @user == current_user %>
    <%= link_to "Edit your account", edit_user_registration_path %>
<% end %>


<h4><%= @user.name %>'s Groups: </h4>
<ul>

    <% @user_groups.each do |group| %>

        <li><%= link_to group.name, group_path(group) %></li>

    <% end %>

</ul>




<h4><%= @user.name %>'s Recent Posts: </h4>
<ul>

    <% @user_posts.last(10).reverse_each do |post| %>

        <li><%= link_to post.content, group_post_path(post.group, post) %> <br>
            In this group: <br>
            <%= link_to post.group.name, group_path(post.group) %> <br>
            <p>&nbsp&nbsp&nbsp&nbsp - Created: <%= post.created_at.strftime("%A, %d %b %Y %l:%M %p") %> UTC </p>
            <br><br>

        </li>

    <% end %>

</ul>




<h4><%= @user.name %>'s Recent Comments: </h4>
<ul>

   <% @user_comments.last(10).reverse_each do |comment| %>

        <li>
            <%= @user.name %> wrote this: <br>
            "<%= comment.content %>" <br>
            On this post: <br>
            <%= link_to comment.post.content, group_post_path(comment.post.group, comment.post) %> 
            <br>
            <p>&nbsp&nbsp&nbsp&nbsp - Created: <%= comment.created_at.strftime("%A, %d %b %Y %l:%M %p") %> UTC </p>            
            <br><br>
        </li>

    <% end %>

</ul>