config/routes.rb
Rails.application.routes.draw do
  
  root 'groups#index'


  #custom routes:
  #
  #
  get '/groups/:id/join_group', to: 'groups#join_group'
  get '/groups/:id/leave_group', to: 'groups#leave_group'
  get '/groups/recently_active', to: 'groups#recently_active', as: "recently_active"
  get '/search_groups', to: 'groups#search', as: "search_groups"
  get '/search_users', to: 'profiles#search', as: "search_users"



  #omniauth routes:
  get '/auth/facebook/callback' => 'sessions#create'

  
  
  #standard routes:
  

  resources :posts, only: [] do
    resources :comments, except: [:index, :show]
  end
  resources :groups do 
    resources :posts, except: [:index]
  end

  
  
  
  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'callbacks' }
  
  resources :profiles, only: [:show]







  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord

    has_many :groups_user
    has_many :users, through: :groups_user
    has_many :posts, dependent: :destroy

    validates :name, presence: :true
    validates :summary, presence: :true

    before_save :update_recent_activity
    after_create :make_admin


    scope :active_in_last_hour, -> { where('recent_activity > ?', 1.hour.ago)}
    scope :active_in_last_day, -> { where('recent_activity > ?', 1.day.ago)}

    
    def update_recent_activity
        self.recent_activity = Time.now
    end
    
    def make_admin
        self.groups_user[0].admin = true
        self.groups_user[0].save
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController


    before_action :set_group, only: [:show, :edit, :update, :join_group, :leave_group, :destroy]
    before_action :user_is_authorized?, only: [:edit, :update, :destroy]
    before_action :authenticate_user!



    def index
        @groups = Group.all
    end
  
    def show
      # @group is set
      @group_users = @group.users
      @group_posts = @group.posts
      respond_to do |format|
        format.html {render :show }
        format.json {render json: @group.to_json(include: { posts: {include: [:user, :comments]}})}
      end
    end
  
    def new
      @group = Group.new
    end
  
    def create
      @group = Group.new(group_params)
      @group.users << current_user
      if @group.save
        flash[:notice] = "You successfully created a group!"
        redirect_to group_path(@group)
      else
        messages = ""
        flash.now[:notice] = @group.errors.full_messages.map {|msg| messages + msg + ". "}[0]
        render 'new'
      end     
    end
  
    def edit  
    end
  
    def update
      if @group.update(group_params)
        redirect_to group_path(@group.id)
      else
        messages = ""
        flash[:notice] = @group.errors.full_messages.map {|msg| messages + msg + ". "}[0]
        redirect_to edit_group_path(@group.id)
      end
    end

    def destroy
      @group.destroy
      redirect_to groups_path
    end

#-----------------------------------


    def join_group
      @group.users << current_user
      flash[:notice] = "You successfully joined this group."
      redirect_to group_path(@group)
    end

    def leave_group
      @group.users -= [current_user]
      flash[:notice] = "You successfully left this group."
      redirect_to group_path(@group)
    end

    def recently_active
      @groups = Group.active_in_last_hour
      flash.now[:notice] = "These groups were active within the last hour!"
      render 'index'
    end

    def search
      @groups = Group.where("name LIKE ?", "%#{params[:group_name_q]}%")
      if params[:group_name_q] == ''
        flash.now[:error] = "You searched for nothing! That returns everything! Deep."
      elsif @groups.empty?
        flash.now[:error] = "No results found for '#{params[:group_name_q]}'!" 
      else
        flash.now[:notice] = "Here are your search results for '#{params[:group_name_q]}'"
      end
      render 'index'
    end



    private
      def group_params
        params.require(:group).permit(:name, :summary)
      end
  
      def set_group
        @group = Group.find(params[:id])
      end

      def user_is_authorized?
        if !current_user.admin?(@group)
          flash[:notice] = "You aren't allowed to do that!"
          redirect_to group_path(@group) 
        end
      end
  
  end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for group do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, :size => 80 %> <br>
  <%= f.label :summary %>
  <%= f.text_field :summary, :size => 110 %> <br>
  <%= f.submit %>
<% end %>

app/views/groups/_group.html.erb
<%= link_to group.name, group_path(group) %> <br>
<%= group.summary %>

app/views/groups/edit.html.erb
<h1>Edit: <%= @group.name %> </h1>

<p><%= render partial: "form", locals: {group: @group} %></p>

app/views/groups/index.html.erb
<div class="card"><div class="card-content"><p><%= link_to "Create a Group", new_group_path %> </p>
<h5> 

    Groups:

</h5>

<ul>

    <% @groups.each do |group| %>
        <li><%= render partial: "group", locals: {group: group}%></li>
        <br>
    <% end %>

</ul>
</div></div>

app/views/groups/new.html.erb
<h1>Create a New Group </h1>

<p><%= render partial: "form", locals: {group: @group} %></p>

app/views/groups/show.html.erb
<!--added this js include tag in order to only load groups.js where necessary (ie this page) -->

<%= javascript_include_tag 'groups' %>


<div class="currentUserId" data-id="<%= current_user.id %>"></div><!--isn't this easily hackable peter?2 -->
<!-- fix it: -->
<!-- https://stackoverflow.com/questions/29737384/accessing-current-user-variable-from-application-js-in-rails-3  -->

<div class="groupShowPage" data-id="true"></div>

<div class="card"><div class="card-content">

<div class='row' id=""><div class='col s12 m12 l12' id="group-show-group-name">
</div></div>


<div class='row'> <div class='col s12 m12' id="group-show-group-summary"><p> 
</p></div></div>


<!-- group_users is still using the rails/ruby object, has not been refactored to using javascript/json -->
<% if @group_users.include?(current_user) %>
    <div class='row'> <div class='col s12 m12'>
        <%= link_to "Leave Group", "/groups/#{@group.id}/leave_group" %> <br>
        <% if current_user.admin?(@group) %>
            <%= link_to "Edit Group", edit_group_path %>
            <%= button_to "Delete Group", group_path, method: :delete %>
        <% end %>
    </div></div>
<% else  %>
    <div class='row'> <div class='col s12 m6'>
        <%= link_to "Join Group", "/groups/#{@group.id}/join_group" %>
    </div></div>
<% end %> <br>



<div class='row'> <div class='col s12 m6'>
    <h1>Posts: </h1>
    <p>(Click the post's text to see its comments.)</p>


    <% if @group_users.include?(current_user) %>
        <div class='row'> <div class='col s12 m12'>
            <h5 id="new-post-link"><%= link_to "New Post", new_group_post_path(@group.id) %></h5>
            
        </div></div>

    <% end %>
    <%= form_for [@group, Post.new] do |f| %>
                <%= f.label :content %>
                <%= f.text_field :content, :size => 80 %> <br>
                <%= f.hidden_field :group_id, value: @group.id %>
                <%= f.submit %>
    <% end %>
   
   
    <form action="" id="userPostQForm">
        <input type="text" name="userPostQ" id="userPostQ" placeholder="Search Posts by Username">
        <input type="submit">
    </form>

    <ul id='group-show-post-list'>
    <!-- <% @group_posts.reverse_each do |post| %>
        
       
        <div class="card blue-grey darken-4">
            <div class="card-content white-text">
            <span class="card-title"><%= link_to post.user.name, profile_path(post.user) %></span>
            <p><%= link_to post.content, group_post_path(@group.id, post.id) %> <br>
            Created: <%= post.created_at.strftime("%A, %d %b %Y %l:%M %p") %> UTC</p>
            </div>
            <div class="card-action">        
            <% if post.user == current_user %>
                <p><%= link_to "Edit Post", edit_group_post_path(@group.id, post.id) %>
                <%= button_to "Delete Post", group_post_path(@group.id, post.id), method: :delete %> </p>
            <% end %>
            </div>
        </div>

     this is the old way:

        <h3><%= link_to post.content, group_post_path(@group.id, post.id) %></h3>
        <p>&nbsp&nbsp&nbsp&nbsp - Written by: <%= link_to post.user.name, profile_path(post.user) %></p> 
        <p>&nbsp&nbsp&nbsp&nbsp - Created: <%= post.created_at.strftime("%A, %d %b %Y %l:%M %p") %> UTC </p>
        <% if post.user == current_user %>
            <p>&nbsp&nbsp&nbsp&nbsp <%= link_to "Edit Post", edit_group_post_path(@group.id, post.id) %> </p>
            <p>&nbsp&nbsp&nbsp&nbsp <%= button_to "Delete Post", group_post_path(@group.id, post.id), method: :delete %> </p>
        <% end %>
        
    <% end %> -->
    </ul>
</div></div>







<div class='row'> <div class='col s12 m6'><h5> Members: </h3>
    <ul>
        <% @group_users.each do |user| %>
            <li>  <%= link_to user.name, profile_path(user) %> </li>
        <% end %>
    </ul>

    <br><br>

    <% if @group_users.include?(current_user) %>
        <%= link_to "Leave Group", "/groups/#{@group.id}/leave_group" %>
    <% else  %>
        <%= link_to "Join Group", "/groups/#{@group.id}/join_group" %>
    <% end %>
</div></div>

</div></div>