config/routes.rb
Rails.application.routes.draw do
  
  root 'groups#index'


  #custom routes:
  #
  #
  get '/groups/:id/join_group', to: 'groups#join_group'
  get '/groups/:id/leave_group', to: 'groups#leave_group'
  get '/groups/recently_active', to: 'groups#recently_active', as: "recently_active"
  get '/search_groups', to: 'groups#search', as: "search_groups"
  get '/search_users', to: 'profiles#search', as: "search_users"



  #omniauth routes:
  get '/auth/facebook/callback' => 'sessions#create'

  
  
  #standard routes:
  

  resources :posts, only: [] do
    resources :comments, except: [:index, :show]
  end
  resources :groups do 
    resources :posts, except: [:index]
  end

  
  
  
  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'callbacks' }
  
  resources :profiles, only: [:show]







  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    belongs_to :group
    has_many :comments

    validates :content, presence: true

    before_save :update_recent_activity


    #the below allows us to keep track of the group's recent activity to which the post belongs
  def update_recent_activity
    self.group.update(recent_activity:  Time.now)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    before_action :authenticate_user!
    before_action :set_post, only: [:show, :edit, :update, :destroy]
    before_action :user_is_authorized?, only: [:edit, :update, :destroy]

    def new
        @post = Post.new
        @post.user = current_user
        @post.group = Group.find(params[:group_id])
    end

    def create
        @post = Post.new(content: post_params[:content], group: Group.find(post_params[:group_id]), user: current_user)
        if @post.save
            # @post.group.update(recent_activity: Time.now)
            # redirect_to group_path(@post.group)
            render json: @post.to_json(include: :user), status: 201
        else
            messages = ""
            flash[:notice] = @post.errors.full_messages.map {|msg| messages + msg + ". "}[0]
            redirect_to new_group_post_path(post_params[:group_id])
        end
    end

    def edit
    end

    def update
        if @post.update(content: post_params[:content])
            redirect_to group_path(@post.group)
        else
            messages = ""
            flash[:notice] = @post.errors.full_messages.map {|msg| messages + msg + ". "}[0]
            redirect_to edit_group_post_path(post_params[:group_id])
        end 
    end 

    def show
        # @post has been set
        respond_to do |format|
            format.html {render :show }
            format.json {render json: @post}
        end
    end

    def destroy
        @post.comments.each {|c| c.destroy}
        @post.group.update(recent_activity: Time.now)
        @post.destroy
        # flash.now[:notice] = "Post deleted."
        # redirect_to group_path(@post.group)
    end

    private

    def post_params
        params.require(:post).permit(:content, :group_id, :id)
    end

    def set_post
        @post = Post.find(params[:id])
    end

    def user_is_authorized?
        if current_user != @post.user
            flash[:notice] = "You aren't allowed to do that!"
            redirect_to group_post_path(@post.group, @post)
        end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for [group, post] do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content, :size => 80 %> <br>
  <%= f.hidden_field :group_id, value: post.group.id %>
  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit post:</h1>

<p><%= render partial: "form", locals: {post: @post, group: @post.group} %></p>

app/views/posts/new.html.erb
<h1>Create a new post:</h1>

<p><%= render partial: "form", locals: {post: @post, group: @post.group} %></p>

app/views/posts/show.html.erb
<h2 class="postContent"> <%= @post.content %></h2>

<h3 class="postGroup">From Group: <%= link_to @post.group.name, group_path(@post.group) %></h3>
<p class="postUsername">&nbsp&nbsp&nbsp&nbsp - Written by: <%= link_to @post.user.name, profile_path(@post.user) %></p> 
<p class="postCreatedAt">&nbsp&nbsp&nbsp&nbsp - Created: <%= @post.created_at.strftime("%A, %d %b %Y %l:%M %p") %> UTC </p>


<p><%= link_to "Create Comment", new_post_comment_path(@post.id) %></p>

<% if !@post.comments.empty? %>
    <h4>Comments...</h4>

                
    <% @post.comments.each do |comment| %>
        <p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp <%= comment.content %></p> 
        <p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp - Written by: <%= link_to comment.user.name, profile_path(comment.user) %></p> 
        <p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp - Created: <%= comment.created_at.strftime("%A, %d %b %Y %l:%M %p") %> UTC </p>
        <% if comment.user == current_user %>
            <p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp <%= link_to "Edit Comment", edit_post_comment_path(@post.id, comment.id) %> </p>
            <p>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp <%= button_to "Delete Comment", post_comment_path(@post.id, comment.id), method: :delete %> </p>
        <% end %>
    <% end %>
<% end %>


<script type="text/javascript" charset="utf-8">
$(function () {
  $(".js-next").on("click", function() {
    var nextId = parseInt($(".js-next").attr("data-id")) + 1;
    $.get("/groups/" + nextId + ".json", function(data) {
      var product = data;
      $(".productName").text(product["name"]);
      $(".productPrice").text(product["price"]);
      $(".productDescription").text(product["description"]);
      $(".productInventory").text(product["inventory"]);
      // re-set the id to current on the link
      $(".js-next").attr("data-id", product["id"]);
    });
  });
});
</script>