config/routes.rb
Rails.application.routes.draw do
  
  root 'groups#index'


  #custom routes:
  #
  #
  get '/groups/:id/join_group', to: 'groups#join_group'
  get '/groups/:id/leave_group', to: 'groups#leave_group'
  get '/groups/recently_active', to: 'groups#recently_active', as: "recently_active"
  get '/search_groups', to: 'groups#search', as: "search_groups"
  get '/search_users', to: 'profiles#search', as: "search_users"



  #omniauth routes:
  get '/auth/facebook/callback' => 'sessions#create'

  
  
  #standard routes:
  

  resources :posts, only: [] do
    resources :comments, except: [:index, :show]
  end
  resources :groups do 
    resources :posts, except: [:index]
  end

  
  
  
  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'callbacks' }
  
  resources :profiles, only: [:show]







  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Activist Network</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> 


  </head>

  <body class="deep-purple lighten-5">
    <nav class="deep-purple darken-4">
      <div class='row'>
        <div class='col m12'>
          <div class="nav-wrapper">
            <div class="">
              <%= link_to "Activist Network", groups_path, class: 'brand-logo' %>
              <% if current_user %>
              <ul id="nav-mobile" class="right hide-on-med-and-down" style="margin-right: 20px">
                <li>Logged in as: <%= current_user.name %>  </li>
                <li><%= link_to "Recently Active Groups", recently_active_path %></li>
                <li><%= link_to "My Page", profile_path(current_user) %></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                <li>
                  <form action="/search_groups" method="GET">
                    <input type="text" placeholder="Search Groups" name="group_name_q">
                  </form>
                </li>

          
      
                <!--<li><%= form_tag("/search_groups", method: "get") do %>
                  
                      <%= label_tag(:group_name_q, "Search Groups") %>
                      <%= text_field_tag(:group_name_q) %>
                      <%= submit_tag("Search") %>
                    
                <% end %></li>

                
                <li><%= form_tag("/search_users", method: "get") do %>
                  
                      <%= label_tag(:group_name_q, "Search Users by Username") %>
                      <%= text_field_tag(:user_name_q) %>
                      <%= submit_tag("Search") %>        
                    

                    ALERT ALERT - THIS HAS A CONTROLLER ACTION AND ROUTE AND EVERYTHING
                    JUST FIGURE OUT HOW TO ADD IT TO YOUR NAVBAR!
                <% end %></li>-->
              </ul>             
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </nav>
  
    
           
    
    

    <div class="container">
      <%# these three lines are working with the devise gem:   %>
      <%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>
      <%= content_tag(:div, flash[:notice], :id => "flash_notice") if flash[:notice] %>
      <%= content_tag(:div, flash[:alert], :id => "flash_alert") if flash[:alert] %>
      <%#--------------------------------%>
      
      <%= yield %>
    </div>
  </body>
</html>